### PR TITLE
Changed path seperator to support compilation on Mac OS

### PR DESCRIPTION
**Pull request by cdhawan**

### CODE REVIEW

**Comment by yuwzho** [comment]
This fix is so important and appreciate!

**Comment by tameraw** [comment]
@cdhawan - Thanks for the PR. We'll review and merge ASAP.

**Comment by cdhawan** [comment]
Thanks @tameraw , there is also a related pull request for azure-iot-arduino library. Kindly consider that as well:

https://github.com/Azure/azure-iot-arduino/pull/43

**Comment by tameraw** [comment]
@cdhawan - Yes. We're looking at the other one as well and will merge them both.

**Comment by mamokarz** [comment]
Merged on version 1.0.30

**Pull request closed without merging**
